[tool.poetry]
name = "colour-datasets"
version = "0.1.1"
description = "Colour science datasets for use with Colour"
license = "BSD-3-Clause"
authors = [ "Colour Developers <colour-developers@colour-science.org>" ]
maintainers = [ "Colour Developers <colour-developers@colour-science.org>" ]
readme = 'README.rst'
repository = "https://github.com/colour-science/colour-datasets"
homepage = "https://www.colour-science.org/"
keywords = [
    "color",
    "color-science",
    "color-space",
    "color-spaces",
    "colorspace",
    "colorspaces",
    "colour",
    "colour-science",
    "colour-space",
    "colour-spaces",
    "colourspace",
    "colourspaces",
    "data",
    "dataset",
    "datasets",
    "python",
    "spectral-data",
    "spectral-dataset",
    "spectral-datasets"
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development"
]

[tool.poetry.dependencies]
python = ">= 3.8, < 3.11"
cachetools = "*"
colour-science = "^0.3.16"
tqdm = "*"
xlrd = ">= 1.2, < 2"

biblib-simple = { version = "*", optional = true }  # Development dependency.
black = { version = "*", optional = true }  # Development dependency.
coverage = { version = "!= 6.3", optional = true }  # Development dependency.
coveralls = { version = "*", optional = true }  # Development dependency.
flake8 = { version = "*", optional = true }  # Development dependency.
flynt = { version = "*", optional = true }  # Development dependency.
invoke = { version = "*", optional = true }  # Development dependency.
mypy = { version = "*", optional = true }  # Development dependency.
numpy = { version = ">= 1.19, < 2", optional = true }
pre-commit = { version = "*", optional = true }  # Development dependency.
pytest = { version = "*", optional = true }  # Development dependency.
pytest-cov = { version = "*", optional = true }  # Development dependency.
pyupgrade = { version = "*", optional = true }  # Development dependency.
restructuredtext-lint = { version = "*", optional = true }  # Development dependency.
sphinx = { version = "*", optional = true }  # Development dependency.
sphinx-rtd-theme = { version = "*", optional = true }  # Development dependency.
sphinxcontrib-bibtex = { version = "*", optional = true }  # Development dependency.
toml = { version = "*", optional = true }  # Development dependency.
twine = { version = "*", optional = true }  # Development dependency.

[tool.poetry.dev-dependencies]
biblib-simple = "*"
black = "*"
coverage = "!= 6.3"
coveralls = "*"
flake8 = "*"
flynt = "*"
invoke = "*"
mypy = "*"
pre-commit = "*"
pytest = "*"
pytest-cov = "*"
pyupgrade = "*"
restructuredtext-lint = "*"
sphinx = "*"
sphinx-rtd-theme = "*"
sphinxcontrib-bibtex = "*"
toml = "*"
twine = "*"

[tool.poetry.extras]
development = [
    "biblib-simple",
    "black",
    "coverage",
    "coveralls",
    "flake8",
    "flynt",
    "invoke",
    "mypy",
    "pre-commit",
    "pytest",
    "pytest-cov",
    "pyupgrade",
    "restructuredtext-lint",
    "sphinx",
    "sphinx-rtd-theme",
    "sphinxcontrib-bibtex",
    "toml",
    "twine",
]
read-the-docs = [ "numpy", "sphinxcontrib-bibtex" ]

[tool.black]
line-length = 79
exclude = '''
/(
    \.git
  | \.mypy_cache
  | build
  | dist
)/
'''

[tool.flynt]
line_length=999

[tool.mypy]
plugins = "numpy.typing.mypy_plugin"
ignore_missing_imports = true

[build-system]
requires = [ "poetry>=0.12" ]
build-backend = "poetry.masonry.api"
